[workspace]
resolver = "3"
members = [
    "crates/wecom",
    "crates/wecom-cli",
    "crates/wecom-transport",
]

[workspace.package]
version = "1.2.1"
license = "MIT"
repository = "https://github.com/WecomTeam/wecom-cli"
homepage = "https://github.com/WecomTeam/wecom-cli"

[workspace.dependencies]
wecom = { version = "1.1.0", path = "crates/wecom", default-features = false }
wecom-transport = { version = "1.1.0", path = "crates/wecom-transport", default-features = false }
anyhow = "1.0.102"
hex = "0.4"
indexmap = { version = "2.13.0", features = ["serde"] }
rand = "0.10"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde_with = { version = "3", features = ["indexmap_2"] }
sha2 = "0.11"
tempfile = "3"
tokio = { version = "1.50.0", features = ["full"] }
tracing = "0.1"

[profile.release]
strip = true
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0
debug = "line-tables-only"
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 3
codegen-units = 16

[profile.test]
opt-level = 0
debug = "line-tables-only"
incremental = true

[profile.test.package."*"]
opt-level = 3
